# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_cuda_compiler_version10.0cudnn7python3.7._:
        CONFIG: osx_64_cuda_compiler_version10.0cudnn7python3.7._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.0cudnn7python3.8._:
        CONFIG: osx_64_cuda_compiler_version10.0cudnn7python3.8._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.0cudnn7python3.9._:
        CONFIG: osx_64_cuda_compiler_version10.0cudnn7python3.9._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.1cudnn7python3.7._:
        CONFIG: osx_64_cuda_compiler_version10.1cudnn7python3.7._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.1cudnn7python3.8._:
        CONFIG: osx_64_cuda_compiler_version10.1cudnn7python3.8._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.1cudnn7python3.9._:
        CONFIG: osx_64_cuda_compiler_version10.1cudnn7python3.9._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.2cudnn8python3.7._:
        CONFIG: osx_64_cuda_compiler_version10.2cudnn8python3.7._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.2cudnn8python3.8._:
        CONFIG: osx_64_cuda_compiler_version10.2cudnn8python3.8._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version10.2cudnn8python3.9._:
        CONFIG: osx_64_cuda_compiler_version10.2cudnn8python3.9._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version11.0cudnn8python3.7._:
        CONFIG: osx_64_cuda_compiler_version11.0cudnn8python3.7._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version11.0cudnn8python3.8._:
        CONFIG: osx_64_cuda_compiler_version11.0cudnn8python3.8._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version11.0cudnn8python3.9._:
        CONFIG: osx_64_cuda_compiler_version11.0cudnn8python3.9._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version11.1cudnn8python3.7._:
        CONFIG: osx_64_cuda_compiler_version11.1cudnn8python3.7._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version11.1cudnn8python3.8._:
        CONFIG: osx_64_cuda_compiler_version11.1cudnn8python3.8._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version11.1cudnn8python3.9._:
        CONFIG: osx_64_cuda_compiler_version11.1cudnn8python3.9._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version9.2cudnn7python3.7._:
        CONFIG: osx_64_cuda_compiler_version9.2cudnn7python3.7._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version9.2cudnn7python3.8._:
        CONFIG: osx_64_cuda_compiler_version9.2cudnn7python3.8._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_version9.2cudnn7python3.9._:
        CONFIG: osx_64_cuda_compiler_version9.2cudnn7python3.9._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_versionNonecudnnNonepython3.7._:
        CONFIG: osx_64_cuda_compiler_versionNonecudnnNonepython3.7._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_versionNonecudnnNonepython3.8._:
        CONFIG: osx_64_cuda_compiler_versionNonecudnnNonepython3.8._
        UPLOAD_PACKAGES: 'True'
      osx_64_cuda_compiler_versionNonecudnnNonepython3.9._:
        CONFIG: osx_64_cuda_compiler_versionNonecudnnNonepython3.9._
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)